### PR TITLE
Fix excessive footer margin and implement proper layout structure

### LINKED ISSUE #21: Bug Report: Excessive Scrolling Required to View Footer
### Describe the Bug

Users must scroll an unreasonably long distance down to view the footer on the home page, even when there are only one or two events displayed. This creates poor user experience and reduces discoverability of important footer content such as contact information and links.

### Cause:
this issue is cause by an excessive top margin in the footer component which is forcing a large gap between the page content and the footer. the gap remains the same regardless of actual content length. 

### Steps to Reproduce

1. Run the project and navigate to any pages starting from the home page
2. Start from an empty events and  add more as you keep observing the gap between the event and footer. 
3. Scrolling a significant distance is required to reach the footer

### Expected Behavior

The footer should:
- Appear with a reasonable margin after the content 
- Be visible without excessive and appropriate visual separation from contetnts

### Visual Aids

<details>
  <summary> Expand ⬇️ </summary>
  
  

https://github.com/user-attachments/assets/6d85f782-81a2-40af-93e3-23ccfc8fd39e

</details>

### Desktop or Mobile Info

_No response_

### Related Issues

_No response_

### Proposed fix:
- modify the footer component to reduce the excessive margin
- update application layout structure to implement proper flex layout, add a container
- check homepage for any container elements with fixed heights

### PR DESCRIPTION
**Pull request by gitbiruk2010**
## Summary & Changes 📃
- **Resolves:** #21 

- **Summary:** Fix excessive footer margin causing poor UX and implement proper layout structure
  - 🔨 What does this issue fix? 
     - Removes excessive 100% top margin on footer that forced users to scroll excessively to see footer content, even on pages with minimal content
  - 👀 What is the expected behavior?
      - Footer appears at a reasonable distance from content (2rem margin) and stays at bottom of viewport on pages with little content
  - 🗨️ Any relevant technical details?
      - Implemented flex layout with proper viewport height management to ensure consistent footer positioning across all pages

- **Changes:**
  - ✅ List key changes made: 
      - Reduced footer component marginTop
      - updated app/layout.tsx to use flex column layout with minheight 100vh
      - added main content area with flex 1 to push footer down when content is minimal
  - 🛠️ Mention breaking changes (if any)
  - 🔗 Link relevant discussions/issues
  - 📝 Additional info to assist developers & reviewers

## Screenshots / Visual Aids 🔎
<sub><i>📌 **Required for:** UI changes, layout updates, or bug fixes.</i></sub>

<details>
  <summary> Expand ⬇️ </summary>
  

https://github.com/user-attachments/assets/72fc1194-b436-4d5c-8eb4-fc54023161c5

</details>

## How to Test 🧪
1. **Steps to Reproduce:**
   - Step 1: Checkout this branch
   - Step 2: Run the project and gab between event contents and footer
   - Step 3: Checkout to your main branch and run the project to see the gap difference between this branch and the main
2. **Expected Behavior:** Footer should appear with reasonable spacing (2rem) below content and stick to bottom of viewport when content is minimal, without requiring excessive scrolling
3. **Actual Behavior (if bug):** Previously required very long scroll to reach footer due to 100% top margin, creating poor user experience

## Checklist ✅

- [ ] I have **tested** this PR **locally** and it works as expected.
- [ ] This PR **resolves an issue** (`Resolves #issue-number`).
- [ ] **Reviewers, assignees(self), tags, and labels** are correctly assigned. 
- [ ] **Squash commits** and enable **auto-merge** if approved.

### CODE REVIEW

File: nsc-events-nextjs/app/page.tsx [hunk 1]
```diff
@@ -89,6 +89,7 @@ const Home = () => {
         flexDirection: "column",
         alignItems: "center",
         m: 2,
+        minHeight: events.length <= 2 ? "calc(100vh - 200px)" : "auto", //this is to dynamically adjust min-height based on event count
```
Comment (NahomAlemu) [inline nsc-events-nextjs/app/page.tsx]: The dynamic min-height gives a cleaner layout when there are few events. A suggestion: instead of hardcoding `calc(100vh - 200px)`, can we derive that offset from the MUI theme `(e.g. theme.spacing(...)` or `theme.mixins.toolbar + theme.layout.footerHeight)`? That avoids a magic number, makes the layout more robust to future design changes, and keeps spacing consistent across the app.

**Review by NahomAlemu — APPROVED** [review]
The extra white space is trimmed and dynamic across all pages. The layout feels much cleaner now. Great improvement overall.

**Review by AzariasANeals — APPROVED** [review]
Tested it out on multiple pages and everything looks great! There is no longer an excessive footer margin. I also like that it allows dynamic adjustments for the min-height based on the event count. I also agree with Nahom's suggestion on using a more dynamic adjustment instead of hardcoding, but I think that this can be done in a later Sprint or issue if necessary.   

https://github.com/user-attachments/assets/93f17fef-a0f3-4358-b3bd-8ede59ae3237

File: nsc-events-nextjs/app/page.tsx (hunk 1 above)
Comment (gitbiruk2010) [reply nsc-events-nextjs/app/page.tsx]: @NahomAlemu, @AzariasANeals Feedback logged! I will be creating a separate issue for other devs to replace the hadcoded viewport calc with theme-based layout constants.

Comment (gitbiruk2010) [reply nsc-events-nextjs/app/page.tsx]: The fix has already been implemented. Given the small scope of the change, a separate issue is not necessary. Good catch @NahomAlemu

**Review by NahomAlemu — APPROVED** [review]
that looks better!

**Comment by katrina-l-hill** [comment]
Great job on this! The big gap between the events and the footer is gone. I was able to test it out and saw that it worked as expected. When I resized the pages, the footer and contents resized with the different pages. Wrapping the content in a flex container was a great move. It ensures that the footer remains anchored and the layout adapts well to different screen sizes. 


https://github.com/user-attachments/assets/f636ad96-bc52-49b5-b2d7-b731bfd9357e
